apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-js-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-js-project
  template:
    metadata:
      labels:
        app: simple-js-project
    spec:
      containers:
        - name: node-container
          image: node:18-alpine
          command: ["node", "/usr/src/app/index.js"] # 运行 Git 仓库中根目录的 index.js 文件
          volumeMounts:
            - name: project-files
              mountPath: /usr/src/app # 挂载 Git 仓库的根目录到容器中的 /usr/src/app
      volumes:
        - name: project-files
          gitRepo:
            repository: https://github.com/qingzhang100/argo_code_example.git # 你的 Git 仓库
            revision: master # 分支名称
            directory: "." # 使用仓库根目录，不要更改
