apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: simple-js-project-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This workflow runs a JavaScript project in a Node.js container.
spec:
  entrypoint: run-js-project
  templates:
    - name: run-js-project
      container:
        image: node:18-alpine
        command: ["node"]
        args: ["index.js"]
        volumeMounts:
          - name: project-files
            mountPath: /usr/src/app
        workingDir: /usr/src/app
  volumes:
    - name: project-files
      gitRepo:
        # My repository
        repository: https://github.com/qingzhang100/argo_code_example.git
