apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: simple-js-project-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This workflow runs a JavaScript project in a Node.js container.
spec:
  entrypoint: run-js-project
  templates:
    - name: run-js-project
      container:
        image: node:18-alpine # Node.js container image
        command: ["node"]
        args: ["/usr/src/app/index.js"] # Full path to index.js
        volumeMounts:
          - name: project-files
            mountPath: /usr/src/app # Mount the Git repository to /usr/src/app
        workingDir: /usr/src/app # Ensure the container's working directory is set correctly
  volumes:
    - name: project-files
      gitRepo:
        repository: https://github.com/qingzhang100/argo_code_example.git # GitHub repository with your project
        revision: master # Specify branch if needed (e.g., "master" or "main")
